# config file for prometheus

global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'fastapi'
    static_configs:
      - targets: ['fastapi:8000']

  - job_name: 'caddy'
    static_configs:
      - targets: ['caddy:9000']

  - job_name: 'flower'
    static_configs:
      - targets: ['celery_flower:9800']
