"""countries

Revision ID: 19defea0d12c
Revises: 5ba558e0815e
Create Date: 2025-04-14 18:12:04.492499

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19defea0d12c'
down_revision: Union[str, None] = '5ba558e0815e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('countries',
    sa.Column('code', sa.String(length=2), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_countries')),
    sa.UniqueConstraint('name', name=op.f('uq_countries_name'))
    )
    op.create_index(op.f('ix_countries_code'), 'countries', ['code'], unique=False)
    op.add_column('proxies_address', sa.Column('country_code', sa.Uuid(), nullable=False))
    op.drop_constraint('uq_proxies_address_country', 'proxies_address', type_='unique')
    op.create_unique_constraint(op.f('uq_proxies_address_country_code'), 'proxies_address', ['country_code', 'region', 'city'])
    op.create_foreign_key(op.f('fk_proxies_address_country_code_countries'), 'proxies_address', 'countries', ['country_code'], ['id'], ondelete='RESTRICT')
    op.drop_column('proxies_address', 'country')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('proxies_address', sa.Column('country', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(op.f('fk_proxies_address_country_code_countries'), 'proxies_address', type_='foreignkey')
    op.drop_constraint(op.f('uq_proxies_address_country_code'), 'proxies_address', type_='unique')
    op.create_unique_constraint('uq_proxies_address_country', 'proxies_address', ['country', 'region', 'city'])
    op.drop_column('proxies_address', 'country_code')
    op.drop_index(op.f('ix_countries_code'), table_name='countries')
    op.drop_table('countries')
    # ### end Alembic commands ###
