"""proxy_health_typo

Revision ID: e4945f64c153
Revises: b4e88ad9d69e
Create Date: 2025-05-02 22:16:51.800242

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e4945f64c153"
down_revision: Union[str, None] = "b4e88ad9d69e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("proxies_health", schema=None) as batch_op:
        batch_op.alter_column(column_name="total_conn_attemps", new_column_name="total_conn_attempts", nullable=False)
        batch_op.alter_column(column_name="failed_conn_attemps", new_column_name="failed_conn_attempts", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("proxies_health", schema=None) as batch_op:
        batch_op.alter_column(column_name="total_conn_attempts", new_column_name="total_conn_attemps", nullable=False)
        batch_op.alter_column(column_name="failed_conn_attempts", new_column_name="failed_conn_attemps", nullable=False)
    # ### end Alembic commands ###
