"""update fk

Revision ID: c9f129cee453
Revises: 95ba570ce574
Create Date: 2025-04-17 20:15:03.358629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9f129cee453'
down_revision: Union[str, None] = '95ba570ce574'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_proxies_geo_address_id_proxies_address', 'proxies', type_='foreignkey')
    op.create_foreign_key(op.f('fk_proxies_geo_address_id_proxies_address'), 'proxies', 'proxies_address', ['geo_address_id'], ['id'], ondelete='RESTRICT')
    op.add_column('proxies_address', sa.Column('country_id', sa.Uuid(), nullable=False))
    op.drop_constraint('uq_proxies_address_country_code', 'proxies_address', type_='unique')
    op.create_unique_constraint(op.f('uq_proxies_address_country_id'), 'proxies_address', ['country_id', 'region', 'city'])
    op.drop_constraint('fk_proxies_address_country_code_countries', 'proxies_address', type_='foreignkey')
    op.create_foreign_key(op.f('fk_proxies_address_country_id_countries'), 'proxies_address', 'countries', ['country_id'], ['id'], ondelete='RESTRICT')
    op.drop_column('proxies_address', 'country_code')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('proxies_address', sa.Column('country_code', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(op.f('fk_proxies_address_country_id_countries'), 'proxies_address', type_='foreignkey')
    op.create_foreign_key('fk_proxies_address_country_code_countries', 'proxies_address', 'countries', ['country_code'], ['id'], ondelete='RESTRICT')
    op.drop_constraint(op.f('uq_proxies_address_country_id'), 'proxies_address', type_='unique')
    op.create_unique_constraint('uq_proxies_address_country_code', 'proxies_address', ['country_code', 'region', 'city'])
    op.drop_column('proxies_address', 'country_id')
    op.drop_constraint(op.f('fk_proxies_geo_address_id_proxies_address'), 'proxies', type_='foreignkey')
    op.create_foreign_key('fk_proxies_geo_address_id_proxies_address', 'proxies', 'proxies_address', ['geo_address_id'], ['id'])
    # ### end Alembic commands ###
