"""fix indexes

Revision ID: 95ba570ce574
Revises: 19defea0d12c
Create Date: 2025-04-17 18:59:31.154156

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95ba570ce574'
down_revision: Union[str, None] = '19defea0d12c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_sources_name'), 'sources', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sources_name'), table_name='sources')
    # ### end Alembic commands ###
