"""initial

Revision ID: 2ea4d91a692b
Revises: 
Create Date: 2025-03-20 20:13:06.535661

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2ea4d91a692b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('proxies_address',
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('region', sa.String(), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_proxies_address')),
    sa.UniqueConstraint('country', 'region', 'city', name=op.f('uq_proxies_address_country'))
    )
    op.create_table('sources',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('uri', sa.String(), nullable=False),
    sa.Column('uri_predefined_type', sa.Enum('HTTP', 'HTTPS', 'SOCKS4', 'SOCKS5', name='protocol'), nullable=True),
    sa.Column('type', sa.Enum('Text', name='sourcetype'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sources'))
    )
    op.create_table('proxies',
    sa.Column('address', postgresql.INET(), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('protocol', sa.Enum('HTTP', 'HTTPS', 'SOCKS4', 'SOCKS5', name='protocol'), nullable=False),
    sa.Column('login', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('geo_address_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['geo_address_id'], ['proxies_address.id'], name=op.f('fk_proxies_geo_address_id_proxies_address')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_proxies')),
    sa.UniqueConstraint('address', 'port', 'protocol', name=op.f('uq_proxies_address'))
    )
    op.create_table('sources_health',
    sa.Column('total_conn_attemps', sa.Integer(), nullable=False),
    sa.Column('failed_conn_attemps', sa.Integer(), nullable=False),
    sa.Column('last_used', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], name=op.f('fk_sources_health_source_id_sources')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sources_health')),
    sa.UniqueConstraint('source_id', name=op.f('uq_sources_health_source_id'))
    )
    op.create_table('proxies_health',
    sa.Column('total_conn_attemps', sa.Integer(), nullable=False),
    sa.Column('failed_conn_attemps', sa.Integer(), nullable=False),
    sa.Column('last_tested', sa.DateTime(timezone=True), nullable=True),
    sa.Column('proxy_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['proxy_id'], ['proxies.id'], name=op.f('fk_proxies_health_proxy_id_proxies')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_proxies_health')),
    sa.UniqueConstraint('proxy_id', name=op.f('uq_proxies_health_proxy_id'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('proxies_health')
    op.drop_table('sources_health')
    op.drop_table('proxies')
    op.drop_table('sources')
    op.drop_table('proxies_address')
    # ### end Alembic commands ###
