"""latency

Revision ID: 5ba558e0815e
Revises: 2ea4d91a692b
Create Date: 2025-04-09 20:59:10.113209

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ba558e0815e'
down_revision: Union[str, None] = '2ea4d91a692b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('proxies_health', sa.Column('latency', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('proxies_health', 'latency')
    # ### end Alembic commands ###
